Force `-release` scalac option to keep Java 8 compatibility, close #124
Motivation:

Code compiled with Java 9+ might not be compatible at runtime with Java 8 because of new overloads that would generate NoSuchMethodError crashes.

Modification:

Force `-release` scalac option to `8`.

Result:

Boopickle can be compiled with Java 11 and still be compatible with Java 8.