Make Boopickle compiled with Java 9+ compatible with Java 8, close #124
Motivation:

Java 9 introduced several overloads to Buffer methods in ByteBuffer:

* position​(int newPosition)
* limit​(int newLimit)
* flip​()
* clear​()
* mark​()
* reset​()
* rewind​()

Compiling such code with Java 9+ with cause it to crash at runtime with Java 8 with NoSuchMethodError.

Modifications:

Introduce a `Java8BufferCompat` helper to force linking to `java.nio.Buffer` methods.

Result:

Boopickle can be compiled with Java 9+ and executed with Java 8.